### ISSUE TITLE
Doesn't work with most formats

### ISSUE THREAD

**Issue by nmn** [torifat/require2import#1]
It fails is:
- You don't put a semicolon at the end of the call
- you don't use var. (It leaves const in front of the import keyword)

Enough people don't use semicolons in JS now. It's fast becoming a best practice.
If you're switching to ES6 it is reasonable to expect some people to use `let` and `const` and not `var`

I will try to make a pull request to fix these issues.

**Comment by torifat** [comment]
Thanks for your feedback. I didn't have enough time yesterday so couldn't give much thought. I will try to incorporate those in the next weekend.

Actually, I made this package out of sheer frustration. Most of the npm packages has `var packageName = require('packageName');` in their `README` and examples. That lead me to use `var` in the first place.

**Comment by torifat** [comment]
- [x] Make semicolon optional
- [x] Add support for `const` & `let`

**Comment by nmn** [comment]
I tried to fix it myself, but I'm not sure I get the regex yet. The `?:` are confusing to me.

I'll take another crack at it later today.

**Comment by torifat** [comment]
@nmn ok, done. `?:` is non capturing group.

**Comment by nmn** [comment]
Thanks... I didn't know that.
